#!/bin/bash
# Script to run Minerva with real AI models
# Generated by MinervaIntegrationFixer

# Run Minerva server with proper error handling and environment setup
set -e  # Exit on any error

echo "======================================="
echo "      Starting Minerva Server          "
echo "======================================="

# Set environment variables
export PORT=5505
export HOST="0.0.0.0"
export FLASK_APP=server.py

# Make sure we're in the right directory
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
cd $SCRIPT_DIR

# Activate virtual environment if it exists
if [ -d "./venv_minerva" ]; then
    echo "Activating virtual environment..."
    source ./venv_minerva/bin/activate
else
    echo "Virtual environment not found, using system Python..."
fi

# Ensure required packages are installed
echo "Checking required packages..."
pip install -q flask flask-socketio flask-cors eventlet python-dotenv

# First run the cleanup script if it exists
if [ -f "./cleanup_codebase.sh" ]; then
    echo "Running codebase cleanup script..."
    ./cleanup_codebase.sh
fi

# Make sure port is not already in use
if lsof -Pi :$PORT -sTCP:LISTEN -t >/dev/null ; then
    echo "Port $PORT is already in use. Killing existing process..."
    pkill -f server.py || true
    sleep 2  # Give it time to shut down
fi

# Start the server in the foreground with proper logging
echo "Starting Minerva server on http://$HOST:$PORT"
echo "Press Ctrl+C to stop"

# Create logs directory if it doesn't exist
mkdir -p logs

# Run the server
python reorganized_server.py 2>&1 | tee logs/minerva_server.log

# Deactivate virtual environment when done
deactivate

# Handle server exit
echo "Server stopped."
